### ISSUE TITLE
Message send with Dealy

### ISSUE THREAD

**Issue by mannuda** [sunilgulabani/aws-sqs-sample#1]
Hi,
Can you please tell me how to send the message with a dealy and receive the same messages in a endless
receiver class.

thank you 
Manish

**Comment by sunilgulabani** [comment]
You can set the Delivery Delay parameter while sending message.

See: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/model/SendMessageRequest.html#setDelaySeconds-java.lang.Integer-

Cheers!!!
